// Provincias y ciudades principales de Argentina
export const provinciasArgentina: Record<string, string[]> = {
  "Buenos Aires": [
    "La Plata",
    "Mar del Plata",
    "Bahía Blanca",
    "Tandil",
    "Quilmes",
    "Lanús",
    "Avellaneda",
    "Lomas de Zamora",
    "Morón",
    "San Isidro",
    "Vicente López",
    "Tigre",
    "Pilar",
    "Zárate",
    "Campana",
    "San Nicolás",
    "Pergamino",
    "Junín",
    "Olavarría",
    "Necochea",
    "Tres Arroyos",
    "Azul",
    "Chivilcoy",
    "Mercedes",
    "Luján",
    "San Pedro",
    "Berazategui",
    "Florencio Varela",
    "Almirante Brown",
    "Esteban Echeverría",
    "Ezeiza",
    "La Matanza",
    "Merlo",
    "Moreno",
    "San Miguel",
    "José C. Paz",
    "Malvinas Argentinas",
    "San Fernando",
    "Escobar",
    "General Rodríguez",
    "Cañuelas",
    "Lobos",
    "Brandsen",
    "Ensenada",
    "Berisso",
    "Otra ciudad"
  ],
  "CABA": [
    "Palermo",
    "Belgrano",
    "Recoleta",
    "Caballito",
    "Villa Crespo",
    "Almagro",
    "Flores",
    "Villa Urquiza",
    "Núñez",
    "Colegiales",
    "Villa Devoto",
    "Villa del Parque",
    "Parque Chas",
    "Saavedra",
    "Coghlan",
    "Villa Pueyrredón",
    "Agronomía",
    "Paternal",
    "Villa Ortúzar",
    "Chacarita",
    "Villa Santa Rita",
    "Monte Castro",
    "Versalles",
    "Villa Real",
    "Villa Luro",
    "Vélez Sársfield",
    "Floresta",
    "Parque Avellaneda",
    "Villa Soldati",
    "Villa Lugano",
    "Villa Riachuelo",
    "Mataderos",
    "Liniers",
    "Parque Chacabuco",
    "Boedo",
    "San Cristóbal",
    "Constitución",
    "San Telmo",
    "Monserrat",
    "San Nicolás",
    "Retiro",
    "Puerto Madero",
    "La Boca",
    "Barracas",
    "Nueva Pompeya",
    "Parque Patricios",
    "Balvanera",
    "Once",
    "Otro barrio"
  ],
  "Catamarca": [
    "San Fernando del Valle de Catamarca",
    "Valle Viejo",
    "Fray Mamerto Esquiú",
    "Andalgalá",
    "Belén",
    "Tinogasta",
    "Santa María",
    "Recreo",
    "Otra ciudad"
  ],
  "Chaco": [
    "Resistencia",
    "Barranqueras",
    "Presidencia Roque Sáenz Peña",
    "Villa Ángela",
    "Charata",
    "General San Martín",
    "Quitilipi",
    "Machagai",
    "Las Breñas",
    "Juan José Castelli",
    "Otra ciudad"
  ],
  "Chubut": [
    "Rawson",
    "Comodoro Rivadavia",
    "Trelew",
    "Puerto Madryn",
    "Esquel",
    "Sarmiento",
    "Gaiman",
    "Rada Tilly",
    "Otra ciudad"
  ],
  "Córdoba": [
    "Córdoba Capital",
    "Villa Carlos Paz",
    "Río Cuarto",
    "Villa María",
    "San Francisco",
    "Alta Gracia",
    "Río Tercero",
    "La Falda",
    "Cosquín",
    "Jesús María",
    "Bell Ville",
    "Villa Dolores",
    "Marcos Juárez",
    "Río Segundo",
    "La Calera",
    "Unquillo",
    "Mendiolaza",
    "Villa Allende",
    "Salsipuedes",
    "Mina Clavero",
    "Otra ciudad"
  ],
  "Corrientes": [
    "Corrientes Capital",
    "Goya",
    "Paso de los Libres",
    "Mercedes",
    "Curuzú Cuatiá",
    "Santo Tomé",
    "Bella Vista",
    "Esquina",
    "Monte Caseros",
    "Otra ciudad"
  ],
  "Entre Ríos": [
    "Paraná",
    "Concordia",
    "Gualeguaychú",
    "Concepción del Uruguay",
    "Gualeguay",
    "Villaguay",
    "Victoria",
    "Colón",
    "Federación",
    "Chajarí",
    "La Paz",
    "Nogoyá",
    "Crespo",
    "Otra ciudad"
  ],
  "Formosa": [
    "Formosa Capital",
    "Clorinda",
    "Pirané",
    "El Colorado",
    "Ingeniero Juárez",
    "Las Lomitas",
    "Otra ciudad"
  ],
  "Jujuy": [
    "San Salvador de Jujuy",
    "Palpalá",
    "San Pedro de Jujuy",
    "Libertador General San Martín",
    "Perico",
    "El Carmen",
    "Tilcara",
    "Humahuaca",
    "La Quiaca",
    "Otra ciudad"
  ],
  "La Pampa": [
    "Santa Rosa",
    "General Pico",
    "Toay",
    "General Acha",
    "Eduardo Castex",
    "Victorica",
    "25 de Mayo",
    "Realicó",
    "Otra ciudad"
  ],
  "La Rioja": [
    "La Rioja Capital",
    "Chilecito",
    "Aimogasta",
    "Chamical",
    "Chepes",
    "Villa Unión",
    "Otra ciudad"
  ],
  "Mendoza": [
    "Mendoza Capital",
    "Godoy Cruz",
    "San Rafael",
    "Guaymallén",
    "Las Heras",
    "Maipú",
    "Luján de Cuyo",
    "Tunuyán",
    "San Martín",
    "Rivadavia",
    "Junín",
    "General Alvear",
    "Malargüe",
    "Tupungato",
    "Otra ciudad"
  ],
  "Misiones": [
    "Posadas",
    "Oberá",
    "Eldorado",
    "Puerto Iguazú",
    "Apóstoles",
    "Jardín América",
    "San Vicente",
    "Leandro N. Alem",
    "Puerto Rico",
    "Montecarlo",
    "Otra ciudad"
  ],
  "Neuquén": [
    "Neuquén Capital",
    "San Martín de los Andes",
    "Villa La Angostura",
    "Cutral Có",
    "Plaza Huincul",
    "Zapala",
    "Centenario",
    "Plottier",
    "Junín de los Andes",
    "Chos Malal",
    "Otra ciudad"
  ],
  "Río Negro": [
    "Viedma",
    "San Carlos de Bariloche",
    "General Roca",
    "Cipolletti",
    "Allen",
    "Villa Regina",
    "El Bolsón",
    "Choele Choel",
    "Catriel",
    "Sierra Grande",
    "Otra ciudad"
  ],
  "Salta": [
    "Salta Capital",
    "San Ramón de la Nueva Orán",
    "Tartagal",
    "General Güemes",
    "Metán",
    "Rosario de la Frontera",
    "Cafayate",
    "San Lorenzo",
    "Cerrillos",
    "Embarcación",
    "Otra ciudad"
  ],
  "San Juan": [
    "San Juan Capital",
    "Rawson",
    "Rivadavia",
    "Chimbas",
    "Santa Lucía",
    "Pocito",
    "Caucete",
    "San Martín",
    "Albardón",
    "Jáchal",
    "Otra ciudad"
  ],
  "San Luis": [
    "San Luis Capital",
    "Villa Mercedes",
    "Merlo",
    "Justo Daract",
    "La Punta",
    "Potrero de los Funes",
    "Juana Koslay",
    "Otra ciudad"
  ],
  "Santa Cruz": [
    "Río Gallegos",
    "Caleta Olivia",
    "El Calafate",
    "Pico Truncado",
    "Puerto Deseado",
    "Las Heras",
    "Puerto San Julián",
    "Perito Moreno",
    "El Chaltén",
    "Otra ciudad"
  ],
  "Santa Fe": [
    "Santa Fe Capital",
    "Rosario",
    "Rafaela",
    "Reconquista",
    "Venado Tuerto",
    "Villa Gobernador Gálvez",
    "Santo Tomé",
    "San Lorenzo",
    "Casilda",
    "Esperanza",
    "Sunchales",
    "San Justo",
    "Firmat",
    "Cañada de Gómez",
    "Villa Constitución",
    "Granadero Baigorria",
    "Funes",
    "Roldán",
    "Otra ciudad"
  ],
  "Santiago del Estero": [
    "Santiago del Estero Capital",
    "La Banda",
    "Termas de Río Hondo",
    "Añatuya",
    "Frías",
    "Fernández",
    "Monte Quemado",
    "Quimilí",
    "Otra ciudad"
  ],
  "Tierra del Fuego": [
    "Ushuaia",
    "Río Grande",
    "Tolhuin",
    "Otra ciudad"
  ],
  "Tucumán": [
    "San Miguel de Tucumán",
    "Yerba Buena",
    "Tafí Viejo",
    "Banda del Río Salí",
    "Concepción",
    "Monteros",
    "Famaillá",
    "Aguilares",
    "Tafí del Valle",
    "Simoca",
    "Juan Bautista Alberdi",
    "Otra ciudad"
  ]
}

export const provincias = Object.keys(provinciasArgentina).sort()

export function getCiudades(provincia: string): string[] {
  return provinciasArgentina[provincia] || []
}
